# Generated by Django 3.2.3 on 2021-05-17 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0003_post_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priorite',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='communitymanager.priorite'),
            preserve_default=False,
        ),
    ]
