# Generated by Django 3.2.3 on 2021-05-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0008_alter_post_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_evenement',
            field=models.DateField(null=True),
        ),
    ]
