# Generated by Django 3.2.3 on 2021-05-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0009_alter_post_date_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_evenement',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
